### ISSUE TITLE
DELETE THIS LIB

### ISSUE THREAD

**Issue by APTEMOH** [rlyonheart/osinteye#2]
Hi, man!

Delete this lib! Do not work, man! ))

[root@ovz1 osinteye]# python3 osinteye --instagram tarussssa
[-] instagram: user not found
[root@ovz1 osinteye]#
[root@ovz1 osinteye]# python3 osinteye --github tarussssa
[-] github: user not found
[root@ovz1 osinteye]#
[root@ovz1 osinteye]# python3 osinteye --github rly0nheart

Richard Mwewa | Github

Richard Mwewa | Github
rly0nheart
Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github

Richard Mwewa | Github
[-] github: user not found

**Comment by rly0nheart** [comment]
Hi @APTEMOH I tested it, and it seems to works fine for me.

**Instagram**
![Screenshot_20220506-132457](https://user-images.githubusercontent.com/74001397/167123494-56cac8e1-7f11-4e6a-8e23-5167ea1f492a.jpg)

**GitHub**
On GitHub, there's no user with this username *tarussssa*, that's why you got a user not found error, next time you should pay attention to what the program tells you.

Lastly, next time you should try to be more polite and respectful, it's been a couple of months since I updated this program and I have never heard anyone complain about it, only you. Before you open an issue to disrespect someone, make sure you know exactly where the problem is coming from. Have a good day:)
